### ISSUE TITLE
iconUrl is not optional

### ISSUE THREAD

**Issue by ZoolWay** [Aluxian/electron-windows-installer#3]
When I do not specify an `iconUrl` option instead of the electron icon I get an error message about an unrecognized URL scheme. Looking at the temporary `.nuspec` file, there is an string with `undefined` for the `iconUrl` element.

When I try to specify an icon with the `file` scheme I do not get any error but end up with the default icon (e.g. `iconUrl: 'file://' + __dirname + 'myicon.png'` or `.ico`). Default means the windows 'no icon' icon...

Some samples would be useful.

**Comment by aluxian** [comment]
According to nuget docs, iconUrl must be an external (i.e. hosted) url:

https://docs.nuget.org/create/nuspec-reference
https://github.com/NuGet/Home/issues/352

So you can't specify a file, sorry. As for the `undefined` error you get when you omit the field, I don't know what to say about that... just by looking at the code, I don't see why it wouldn't work and I don't have a Windows machine at hand to test.

Until you get to host your own icon somewhere available, I recommend you use the icon from the example/test, or any png icon on the internet.

I agree that some samples would be useful, I was confused as hell when I started working with Electron and Squirrel.Windows. But slowly, things got clearer, because Electron is powered by a very active community. Let me know if you have any other questions.

**Comment by ZoolWay** [comment]
Ok, thanks!
